import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css"
          integrity="sha384-oS3vJWb5lS2jR9Xh6D7D6j5j5su65ANkP2Xk2pJv9yy6cF94Rvh6+Vi3X8P1hj+A"
          crossOrigin="anonymous"
        />
      </head>
      <body
        className={`h-screen flex flex-col gap-8  justify-between`}
      >
        <Header />
        {children}
        <Footer/>
      </body>
    </html>
  );
}
